  os: osx
  osx_image: xcode11.3
  compiler: clang
  before_install:
    - curl -k https://curl.se/ca/cacert.pem -o /tmp/cacert.pem
    - export CURL_CA_BUNDLE=/tmp/cacert.pem
    - brew update
    - brew install qt5 libogg libsndfile libvorbis pkg-config portaudio jack lame
  before_script:
    - brew link qmake
  script:
    - mkdir ./build2
    - cd ./build2
    - cmake -P ../build.cmake -DCMAKE_BUILD_TYPE=Release
