  os: osx
  osx_image: xcode11.3
  compiler: clang
  addons:
    homebrew:
      packages:
        - ca-certificates
        - qt
        - libogg
        - libsndfile
        - libvorbis
        - portaudio
        - jack
        - lame
      update: true
  before_script:
    - brew link qmake
  script:
    - mkdir ./build2
    - cd ./build2
    - cmake -P ../build.cmake -DCMAKE_BUILD_TYPE=Release
